### ISSUE TITLE
Shorten project titles longer than 1 line

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#107]
On the iPad, longer project titles weren't shortened enough to maintain 1 line of text:

![photo 8 ](https://f.cloud.github.com/assets/901048/193036/6748a5e4-7f76-11e2-91e8-49e952a3d31d.PNG)

**Comment by gsaines** [comment]
Still seeing this on iPad Safari and Chrome after clearing all browsing data for both.

**Comment by juliasolorzano** [comment]
@gsaines and I verified that this is working. :dango: for everyone!
