### ISSUE TITLE
Blank projects on the explore page

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#108]
Blank projects are being introduced to the explore page. At first I thought this was only being triggered when going between landscape and portrait modes, but after our Raspberry checkin earlier, moving between the two modes appears to be unrelated to the problem. The blank projects are not clickable:

![photo 7 ](https://f.cloud.github.com/assets/901048/193048/d389d19c-7f76-11e2-9e41-208002c2e980.PNG)

**Comment by gsaines** [comment]
I'm still seeing this on the iPad (where it was originally spotted). I've tried it on both Chrome and Safari, tried clearing the cache, reloading the page.

**Comment by juliasolorzano** [comment]
@gsaines and I verified that this is working too. :dango: :dango: and :dango:
