### ISSUE TITLE
Add "Delete Step," "Delete Project," and "Cancel Project"

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#109]
We need to enable users to cancel what they are currently doing when creating projects and project steps and also delete content that they create.
- [x] On the "Add project step" page, we need a "Cancel" button at the bottom next to the Save and Preview buttons.
- [x] On the create project page, we need a Cancel button.
- [x] On a project page, we need a "Delete Project" button next to the edit buttons at the top.
- [x] On a project page, we need a "Delete Project Step" button next to the "edit step" buttons
- [x] We need to style the delete button appropriately so that they look dangerous

**Comment by daaray** [comment]
#111
