### ISSUE TITLE
Investigate mezzanine migration error

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#11]
The following error is thrown when the mezzanine.pages migrations run:

FATAL ERROR - The following SQL query failed: ALTER TABLE "pages_contentpage_id_seq" RENAME TO "pages_richtextpage_id_seq";
The error was: relation "pages_contentpage_id_seq" does not exist

When running unit tests, we have `SOUTH_TESTS_MIGRATE` set to True, so the error recurs each time. This probably isn't a severe problem but we may need to investigate this eventually

**Comment by calebsmith** [comment]
Just a quick note, this no longer appears in the test suite on the develop branch because SOUTH_TESTS_MIGRATE is set to False and sqlite is used in the test suite.

**Comment by gsaines** [comment]
Has this been resolved?
