### ISSUE TITLE
Compress more things and use a minifier

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#122]
We are currently compressing the site.js and site.less files. This allows us to offline the less compilation but it would be even more helpful if we started using a css and a js minifier.

We could also start wrapping the {% compress %} tags around various js and css files throughout our templates. However, I'm not a huge fan of the {% if debug %} boilerplate that this currently requires, so finding a better solution for this would be ideal.

**Comment by juliasolorzano** [comment]
@calebsmith we might want to try using {% spaceless %} in base.html. I am always a little skeptical about using it, since it can mess up the layout at times. 
- [x] Test out  `{% spaceless %}` on base.html

**Comment by calebsmith** [comment]
I think the remaining work for this ticket will be to find where we can compress some of the remaining static assets, such as the jquery file uploader.
