### ISSUE TITLE
Create page explaining why users should join the site

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#127]
From an email from Jason Huggins:

I think the "Get Started" link should not go to a "Create Account"
page. It should probably go to something like a "Wha?" page explaining
why this site exists. More specifically, explain what I'll get to see
(or do) after I create an account. I don't want to create an account
first. I want to know why I should bother creating an account.

**Comment by juliasolorzano** [comment]
Fixed here: http://raspberry.io/about-raspberry-io/
