### ISSUE TITLE
Fix wiki preview (again)

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#130]
The wiki preview is broken since upgrading to 0.0.17. @daaray's fork changes its requirement to Pillow in lieu of PIL. We'll need to make this requirements change in 0.0.15 of the django-wiki form and pin that in the raspberryio requirements.

This is a result of template overrides that we needed to make that break as a result of changes in template structure of 0.0.15 to 0.0.17 of django-wiki

**Comment by daaray** [comment]
https://github.com/daaray/django-wiki/tree/0.0.15-pillow

**Comment by calebsmith** [comment]
Thanks for the help @daaray. I think we've got the wiki previews working correctly again. (and pillow)
