### ISSUE TITLE
Configure SSL URLS

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#140]
Noah is going to setup SSL before Wednesday. We'll need to tinker with the settings to ensure the appropriate URLs are routed through SSL.

http://mezzanine.jupo.org/docs/configuration.html#ssl-enabled

**Comment by vkurup** [comment]
This is in progress. The servers are currently behind fastly but Noah will be undoing that, at which point SSL will work again.

**Comment by vkurup** [comment]
This is done, but I need to fix the links to the jquery CDN since code.jquery.com is not behind HTTPS. Will open a new ticket.

**Comment by vkurup** [comment]
Oops. Closed this one too fast. HTTPS has been set up, but I don't think any of the Mezzanine settings are implemented yet.

**Comment by vkurup** [comment]
Now this is done.
