### ISSUE TITLE
Follow/Unfollow buttons stuck in "Follow" display

### ISSUE THREAD

**Issue by ironfroggy** [python/raspberryio#144]
Even for people I"m following, but not all the time. Example: constantly shows "Follow" for Julia and Caleb, even tho I'm following them. If I click again, it seems to unfollow, so this could be leading to people mistakenly dropping friends.

**Comment by calebsmith** [comment]
I can't seem to reproduce this. It may well be that the "Following" text that shows when someone is in your list of followees is too confusing, and seems to be a "follow" button?
