### ISSUE TITLE
Mezzanine requires a site to be created, and asks for it during syncdb

### ISSUE THREAD

**Issue by Scottm-Caktus** [python/raspberryio#2]
Mezzanine requires a site to be created, and asks for it during syncdb. 

The Fabric script runs "'syncdb --noinput" This causes gunicorn errors.

**Comment by gsaines** [comment]
Has anything changed WRT this issue?

**Comment by daaray** [comment]
We should just test if removing `noinput` from the syncdb task in the fabfile has any unforeseen affects. It should be fine.
