### ISSUE TITLE
avatar upload doesn't save file

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#39]

**Comment by calebsmith** [comment]
The relevant mezzanine code in github appears to handle the profile form correctly, passing request.FILES into the profile form constructor when signing up or editing a profile:

https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/accounts/views.py#L52
https://github.com/stephenmcd/mezzanine/blob/master/mezzanine/accounts/views.py#L137

However, the latest git tag is for v1.1.2 while the latest version of the package on PYPI is 1.3.0. We might need to point our pip requirements at github for this package but I'm not certain what other breakage might result.

**Comment by daaray** [comment]
The vX.X.X look like anomalies in the naming schema. v1.1.2 is 8 months old, v1.3 is 2 months old, they are just listed in an odd order.

**Comment by daaray** [comment]
https://github.com/stephenmcd/mezzanine/commit/cf98a8e21e23cefe92df0c80df073807315ec3a7

This commit is 1 month old. 1.3.0 is 2 months old. I suggest updating the requirement to pull from the latest master commit, until such a point in time 1.3.X comes out.
