### ISSUE TITLE
Integrate Wiki solution

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#42]
The site will have a section that allows for collaborative curriculum/materials editing.  The desire is to have this section be a Wiki.

Based off of a brief overview of [Django Wikis](https://www.djangopackages.com/grids/g/wikis/):
- [x] Integrate [django-wiki](https://github.com/benjaoming/django-wiki)
- [x] Trigger appropriate actions for activity-stream (Add Wiki Page, Edit Wiki Page)
- [ ] Integrate into search solution

**Comment by vkurup** [comment]
Integrated and worked into activity stream with PR #51.
