### ISSUE TITLE
"Pick your username" on homepage needs to link to registration form.

### ISSUE THREAD

**Issue by juliasolorzano** [python/raspberryio#49]
Currently, this form is static and does not do much. Here is the interaction I was thinking about:
- User enters username 
- Selects "continue"
- Form posts to /account/signup/ with the username field already filled in

It could be username or first name. Since username's are required, I assumed that would be the best solve.

**Comment by juliasolorzano** [comment]
@daaray and @calebsmith felt that we need to slate this for a later date, if necessary at all. Pushing in to Phase 2.

**Comment by gsaines** [comment]
This design element has been removed from the site, which seems to invalidate this issue.
