### ISSUE TITLE
Featured project on homepage

### ISSUE THREAD

**Issue by juliasolorzano** [python/raspberryio#50]
Need to determine how projects are chosen as featured on the homepage.

**Comment by daaray** [comment]
TODO:
- [x] Create FeaturedProject Model
  - byline
  - photo
  - OnetoOne to Project
- [x] Wire up home page view to pull latest FeaturedProject with an underling Published Project.
- [x] Validator to ensure photo is min 1252x626 for the homepage

**Comment by daaray** [comment]
#50
