### ISSUE TITLE
Aggregator management command needs to be on a cron job

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#59]
There is a management command that sends a mail message informing of pending feeds to be added. This needs to be placed on a cron, or rewritten to send out the notification in real time.

**Comment by daaray** [comment]
Added **aggregator_approval_reminder** to `/etc/cron.d`

15 7 \* \* \* raspberryio /home/raspberryio/www/staging/env/bin/django-admin.py  send_pending_approval_email --settings=raspberryio.settings.staging

Will verify in the AM whether or not this version works, as we need to run that job as the particular user for the database connection.

**Comment by calebsmith** [comment]
Verified to work. Planning to place cron on production once basic auth can be removed
