### ISSUE TITLE
Add gravatar option for user avatar

### ISSUE THREAD

**Issue by juliasolorzano** [python/raspberryio#6]
Users should be able to use their gravatar, instead of uploading an image:
https://en.gravatar.com/site/implement/

**Comment by daaray** [comment]
There is a templatetag in Mezzanine that will pull in a gravatar:

http://mezzanine.jupo.org/docs/packages.html?highlight=gravatar#mezzanine.core.templatetags.mezzanine_tags.gravatar_url

We'd just need to store the email a user has used to generate their gravatar in the userprofile.

**Comment by daaray** [comment]
Current Plan:
- Support Avatar or Gravatar
- If Avatar uploaded, use that
- If no Avatar, find a gravatar
- If neither, default to default STATIC profile image
