### ISSUE TITLE
Wiki Modifications

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#60]
We need to not expose some default wiki functionality for the sake of time and not confusing the end user:
- [x] Remove Notifications widget(s) in the Wiki template
- [x] Remove Notification checkbox in Wiki Article Settings **When this article is edited**
- [x] Change Language for **Receive Emails about article edits** (remove _Also_)

**Comment by vkurup** [comment]
Also, I think that the email notification behavior might not be built into django-wiki. At least the README here suggests that: https://github.com/benjaoming/django-wiki/tree/master/django_notify

So, it might be best just to remove all of the Notification settings from the wiki...

OK, I'll go back to lurking :)

**Comment by daaray** [comment]
:dango:
