### ISSUE TITLE
WYSYWYG doesn't appear for non superusers

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#71]
The rich text fields appear as plain text fields for non superusers. I noticed this in the work for the qanda app, but I think it is an existing problem in the project app, and basically project wide.

Without looking into it, my assumption is that this is a default part of mezzanine's rich text field

We usually QA with superusers, so I think this has fallen through the cracks. I think this explains the feedback regarding lack of WYSYWYG support for project submission.

**Comment by calebsmith** [comment]
I just confirmed this for the project submission forms locally

**Comment by daaray** [comment]
Notes: The tinymce resources are never even requested when logged in as a non-superuser....they are definitely accessible if one directly loads them in the URL bar, so it must be a template/configuration we have overlooked, vs a permissions issue.

**Comment by calebsmith** [comment]
Found the answer at:

https://groups.google.com/forum/?fromgroups=#!msg/mezzanine-users/foWr3FYG7D4/FpRiPIdlzVIJ

{{ form.media }} (where form is the variable name for the form in the template), has to be used everywhere.
