### ISSUE TITLE
Enable text rollover state on projects page

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#80]
Karen mentioned that the project photos didn't communicate the purpose of the project very clearly in her feedback email:

"I find it disconcerting to have no text for the projects on the project exploration page. The images alone I fear are not going to convey much."

Julia's suggestion was to add a rollover state for the images that displays written information about the project contents.

**Comment by juliasolorzano** [comment]
I spoke with @kmtracey about how to move forward with this interaction. While the rollover text would be neat, it still hides exactly what the purpose of this site is BUT, this might be an interesting addition in a later phase.
