### ISSUE TITLE
Set ALLOWED_HOSTS

### ISSUE THREAD

**Issue by calebsmith** [python/raspberryio#89]
Upgraded to latest Django stable release a moment ago, but we'll need to set the ALLOWED_HOSTS setting to prevent the header poisoning vulernability:

https://www.djangoproject.com/weblog/2013/feb/19/security/

**Comment by mlavin** [comment]
The Nginx configuration already denies non-matching HOST headers before they get to Django https://github.com/caktus/raspberryio/blob/master/conf/templates/nginx/site.conf#L17 but there are several other fixes that might be relevant and obviously this should be upgraded.
