### ISSUE TITLE
Compressor falling over

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#91]
Deployment fails as the compressor settings are no longer found....

**Comment by daaray** [comment]
Related: https://github.com/jezdez/django_compressor/issues/333 ?

**Comment by daaray** [comment]
We determined this was related to a PR merge that was causing import time errors. Reverted repo and re-branched to resolve the issue separately.

**Comment by carltongibson** [comment]
Linking this to jezdez/django-appconf#13
