### ISSUE TITLE
Add top 5 active users to front page

### ISSUE THREAD

**Issue by daaray** [python/raspberryio#96]
To highlight the community aspect of the site, the front page should showcase some aspect(s) of said community.

The initial pass will expose the top 5 active users on the front page, below the Featured Project.

**Comment by daaray** [comment]
Needs styling from the Style Guru, @juliaelman

**Comment by juliasolorzano** [comment]
2a757cf00,  1c0cbc09d, 8aa6ed098, 490d3199 relate to the styling here. Pushed to staging!
