### ISSUE TITLE
Remove "Logged Out" popup dialogue

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#98]
If you login, visit the homepage, and then logout, a confirmation message telling the user they have logged out appears right below the header. It looks disconnected from the rest of the interface, and I believe we had agreed to remove it.

**Comment by juliasolorzano** [comment]
@gsaines I added a "fade out" for all alert messages, including the logged out message here: fb85c2b0d44 We talked about NOT removing the message and doing this instead. It is nice to have some sort of communication to the user stating that have been successful with the logged out action. Removing it did not seem like a good solve.
