### ISSUE TITLE
Favicon not showing up

### ISSUE THREAD

**Issue by gsaines** [python/raspberryio#99]
I am unable to get the favicon to display, reloading and clearing the cache have not worked. Relatively low priority issue, but wanted to document it.

**Comment by juliasolorzano** [comment]
@gsaines is that on all devices or on a particular device?

**Comment by gsaines** [comment]
My iPad, iPod, and Android phones don't appear to load favicons for any sites, so the only platform on which I've noticed the absence is my laptop.

**Comment by juliasolorzano** [comment]
@gsaines so, mobile devices do not use favicons. We currently do not have Apple touch icons created, but that would not solve this issue and a new issue should be opened to create these.

My recommendation is to clear your cache and restart the browser.

**Comment by gsaines** [comment]
Just cleared my cache again and it resolved this one (doh!) :dango:
